BlogMichel.Web/Models/Blog/DetalhesPostViewModel.cs
using BlogMichel.DB.Classes;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BlogMichel.Web.Models.Blog
{
    public class DetalhesPostViewModel
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public DateTime DataPublicacao { get; set; }
        public string Autor { get; set; }
        public bool Visivel { get; set; }
        public string Resumo { get; set; }
        public int QtdeComentarios { get; set; }
        public string Descricao { get; set; }
        public IList<TagClass> Tags { get; set; }
        
        /*CADASTRAR COMENTARIO*/

        [DisplayName("Nome")]
        [StringLength(100, ErrorMessage = "O campo Nome deve possuir no máximo {1} caracteres!")]
        [Required(ErrorMessage = "O campo Nome é obrigatório!")]
        public string ComentarioNome { get; set;}
        [DisplayName("E-mail")]
        [StringLength(100, ErrorMessage = "O campo E-mail deve possuir no máximo {1} caracteres!")]
        [Required(ErrorMessage = "O campo E-mail é obrigatório!")]
        public string ComentarioEmail { get; set; }
        [DisplayName("Descrição")]
        [StringLength(100, ErrorMessage = "O campo Descrição deve possuir no máximo {1} caracteres!")]
        [Required(ErrorMessage = "O campo Descrição é obrigatório!")]
        public string ComentarioDescricao { get; set; }
        [DisplayName("Página Web")]
        [StringLength(100, ErrorMessage = "O campo Página Web deve possuir no máximo {1} caracteres!")]
        [Required(ErrorMessage = "O campo Página Web é obrigatório!")]
        public string ComentarioPaginaWeb { get; set; }

        /*LISTAR COMENTARIOS*/
        public int PaginaAtual { get; set; }
        public int TotalPaginas { get; set; }
        public IList<Comentario> Comentarios { get; set; }

    }
}

BlogMichel.Web/Models/Blog/ListarPostsViewModel.cs
using BlogMichel.DB.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogMichel.Web.Models.Blog
{
    public class ListarPostsViewModel
    {
        public List<DetalhesPostViewModel> Posts { get; set; }
        public int PaginaAtual { get; set; }
        public int TotalPaginas { get; set; }
        public string Tag { get; set; }
        public List<string> Tags { get; set; }
        public string Pesquisa { get; set; }
    }
}

BlogMichel.Web/Controllers/AdministracaoController.cs
using BlogMichel.DB;
using BlogMichel.DB.Classes;
using BlogMichel.Web.Models.Administracao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogMichel.Web.Controllers
{
    public class AdministracaoController : Controller
    {
        #region Index
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region ExcluirPost
        public ActionResult ExcluirPost(int id)
        {
            var conexaoBanco = new conexaoBanco();
            var post = (from p in conexaoBanco.Posts
                        where p.Id == id
                        select p).FirstOrDefault();
            if (post == null)
            {
                throw new Exception(string.Format("Post código {0} não existe.", id));
            }
            conexaoBanco.Posts.Remove(post);
            conexaoBanco.SaveChanges();

            return RedirectToAction("Index", "Blog");
        }
        #endregion
        #region ExcluirComentario
        public ActionResult ExcluirComentario(int id)
        {
            var conexaoBanco = new conexaoBanco();
            var comentario = (from p in conexaoBanco.Comentarios
                              where p.Id == id
                              select p).FirstOrDefault();
            if (comentario == null)
            {
                throw new Exception(string.Format("Comentário código {0} não foi encontrado.", id));
            }
            conexaoBanco.Comentarios.Remove(comentario);
            conexaoBanco.SaveChanges();

            var post = (from p in conexaoBanco.Posts
                        where p.Id == comentario.IdPost
                        select p).First();
            return Redirect(Url.Action("Post", "Blog", new
            {
                ano = post.DataPublicacao.Year,
                mes = post.DataPublicacao.Month,
                dia = post.DataPublicacao.Day,
                titulo = post.Titulo,
                id = post.Id
            }) + "#comentarios");
        }
        #endregion

        #region CadastrarPost
        public ActionResult CadastrarPost()
        {
            var viewModel = new CadastrarPostViewModel();
            viewModel.DataPublicacao = DateTime.Now;
            viewModel.HoraPublicacao = DateTime.Now;
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult CadastrarPost(CadastrarPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var conexao = new conexaoBanco();
                var post = new Post();
                post.DataPublicacao = new DateTime(
                     viewModel.DataPublicacao.Year,
                     viewModel.DataPublicacao.Month,
                     viewModel.DataPublicacao.Day,
                     viewModel.HoraPublicacao.Hour,
                     viewModel.HoraPublicacao.Minute, 0);

                post.Titulo = viewModel.Titulo;
                post.Resumo = viewModel.Resumo;
                post.Autor = viewModel.Autor;
                post.Descricao = viewModel.Descricao;
                post.Visivel = viewModel.Visivel;
                post.TagsPost = new List<TagPost>();
                if (viewModel.Tags != null)
                {
                    foreach (var item in viewModel.Tags)
                    {
                        var tagExiste = (from p in conexao.TagClass
                                         where p.Tag.ToLower() == item.ToLower()
                                         select p).Any();
                        if (!tagExiste)
                        {
                            var tagClass = new TagClass();
                            tagClass.Tag = item;
                            conexao.TagClass.Add(tagClass);
                            {
                                var tagPost = new TagPost();
                                tagPost.IdTag = item;
                                conexao.TagPosts.Add(tagPost);

                            }
                        }
                    }
                }

                conexao.Posts.Add(post);
                try
                {
                    conexao.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("Erro no banco", exp.Message);
                }

            }
            return View(viewModel);
        }
        #endregion

        public ActionResult EditarPost(int id)
        {
            var conexao = new conexaoBanco();

            var post = (from x in conexao.Posts
                        where x.Id == id
                        select x).FirstOrDefault();
            if (post == null)
            {
                throw new Exception(string.Format("Post com código {0} não encontrado.", id));
            }
            var viewmodel = new CadastrarPostViewModel();
            viewmodel.DataPublicacao = post.DataPublicacao;
            viewmodel.HoraPublicacao = post.DataPublicacao;
            viewmodel.Autor = post.Autor;
            viewmodel.Titulo = post.Titulo;
            viewmodel.Resumo = post.Resumo;
            viewmodel.Descricao = post.Descricao;
            viewmodel.Visivel = post.Visivel;
            viewmodel.Id = post.Id;
            viewmodel.Tags = (from p in post.TagsPost
                              select p.IdTag).ToList(); 
                       
            return View(viewmodel);

        }
        [HttpPost]
        public ActionResult EditarPost(CadastrarPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var conexao = new conexaoBanco();
                var post = (from x in conexao.Posts
                            where x.Id == viewModel.Id
                            select x).FirstOrDefault();
                post.DataPublicacao = viewModel.DataPublicacao;
                post.HoraPublicacao = viewModel.DataPublicacao;
                post.Autor = viewModel.Autor;
                post.Titulo = viewModel.Titulo;
                post.Resumo = viewModel.Resumo;
                post.Descricao = viewModel.Descricao;
                post.Visivel = viewModel.Visivel;
                post.Id = viewModel.Id;


                var postsTagsAtuais = post.TagsPost.ToList();
                foreach (var item in postsTagsAtuais)
                {
                    conexao.TagPosts.Remove(item);
                }
                if (viewModel.Tags != null)
                {
                    foreach (var item in viewModel.Tags)
                    {
                        var tagExiste = (from p in conexao.TagClass
                                         where p.Tag.ToLower() == item.ToLower()
                                         select p).Any();
                        if (!tagExiste)
                        {
                            var tagClass = new TagClass();
                            tagClass.Tag = item;
                            conexao.TagClass.Add(tagClass);
                            {
                                var tagPost = new TagPost();
                                tagPost.IdTag = item;
                                conexao.TagPosts.Add(tagPost);

                            }
                        }
                    }
                }


                try
                {
                    conexao.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("Erro no banco", exp.Message);
                }
            }
            return View(viewModel);
        }

    }
}

BlogMichel.Web/Controllers/BlogController.cs
using BlogMichel.DB;
using BlogMichel.DB.Classes;
using BlogMichel.Web.Models.Blog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogMichel.Web.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index(int? pagina, string tag, string pesquisa)
        {
            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registrosPorPagina = 10;


            var conexaoBanco = new conexaoBanco();

            var posts = (from p in conexaoBanco.Posts
                         where p.Visivel == true
                         select p);
            if (!string.IsNullOrEmpty(tag))
            {
                posts = (from p in posts
                         where p.TagsPost.Any(x => x.IdTag.ToUpper() == tag.ToUpper())
                         select p);
            }
            if (!string.IsNullOrEmpty(pesquisa))
            {
                posts = (from p in posts
                         where p.Titulo.ToUpper().Contains(pesquisa.ToUpper())
                         || p.Resumo.ToUpper().Contains(pesquisa.ToUpper())
                         || p.Descricao.ToUpper().Contains(pesquisa.ToUpper())
                         select p);
            }
            var qtdeRegistros = posts.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdeRegistrosPular = (indiceDaPagina * registrosPorPagina);
            var qtdePaginas = Math.Ceiling((decimal)qtdeRegistros / registrosPorPagina);

            var viewModel = new ListarPostsViewModel();
            viewModel.Posts = (from p in posts
                               orderby p.DataPublicacao descending
                               select new DetalhesPostViewModel
                               {
                                   DataPublicacao = p.DataPublicacao,
                                   Autor = p.Autor,
                                   Descricao = p.Descricao,
                                   Id = p.Id,
                                   Resumo = p.Resumo,
                                   Titulo = p.Titulo,
                                   Visivel = p.Visivel,
                                   QtdeComentarios = p.Comentarios.Count
                                }).Skip(qtdeRegistrosPular).Take(registrosPorPagina).ToList();
            viewModel.PaginaAtual = paginaCorreta;
            viewModel.TotalPaginas = (int)qtdePaginas;
            viewModel.Tag = tag;
            viewModel.Tags = (from p in conexaoBanco.TagClass
                              where conexaoBanco.TagPosts.Any(x => x.IdTag == p.Tag)
                              orderby p.Tag
                              select p.Tag).ToList();
            viewModel.Pesquisa = pesquisa;

            return View(viewModel);
        }
        public ActionResult _Paginacao()
        {
            return PartialView();
        }
        #region Post
        public ActionResult Post(int id, int? pagina)
        {
            var conexaoBanco = new conexaoBanco();
            var post = (from p in conexaoBanco.Posts
                        where p.Id == id
                        select p).FirstOrDefault();
            if (post == null)
            {
                throw new Exception(string.Format("Post com código {0} não encontrado.", id));
            }

            var viewModel = new DetalhesPostViewModel();
            preencherViewModel(post, viewModel, pagina);
            return View(viewModel);

        }

        private void preencherViewModel(Post post, DetalhesPostViewModel viewModel, int? pagina)
        {
            viewModel.Id = post.Id;
            viewModel.Autor = post.Autor;
            viewModel.DataPublicacao = post.DataPublicacao;
            viewModel.Titulo = post.Titulo;
            viewModel.Resumo = post.Resumo;
            viewModel.Visivel = post.Visivel;
            viewModel.QtdeComentarios = post.Comentarios.Count;
            viewModel.Descricao = post.Descricao;
            viewModel.Tags = post.TagsPost.Select(x => x.TagClass).ToList();
            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registrosPorPagina = 10;
            var qtdeRegistros = post.Comentarios.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdeRegistrosPular = (indiceDaPagina * registrosPorPagina);
            var qtdePaginas = Math.Ceiling((decimal)qtdeRegistros / registrosPorPagina);
            viewModel.Comentarios = (from p in post.Comentarios
                                     orderby p.DataHora descending
                                     select p).Skip(qtdeRegistrosPular).Take(registrosPorPagina).ToList();
            viewModel.PaginaAtual = paginaCorreta;
            viewModel.TotalPaginas = (int)qtdePaginas;          
        }

        [HttpPost]
        public ActionResult Post(DetalhesPostViewModel viewModel)
        {
            var ConexaoBanco = new conexaoBanco();
            var post = (from p in ConexaoBanco.Posts
                        where p.Id == viewModel.Id
                        select p).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (post == null)
                {
                    throw new Exception(string.Format("Post código {0} não encontrado.", viewModel.Id));
                }

                var comentario = new Comentario();
                comentario.AdmPost = HttpContext.User.Identity.IsAuthenticated;
                comentario.Descriçao = viewModel.ComentarioDescricao;
                comentario.Email = viewModel.ComentarioEmail;
                comentario.IdPost = viewModel.Id;
                comentario.Nome = viewModel.ComentarioNome;
                comentario.PaginaWeb = viewModel.ComentarioPaginaWeb;
                comentario.DataHora = DateTime.Now;

                try
                {
                    ConexaoBanco.Comentarios.Add(comentario);
                    ConexaoBanco.SaveChanges();
                    return Redirect(Url.Action("Post", new
                    {
                        ano = viewModel.DataPublicacao.Year,
                        mes = viewModel.DataPublicacao.Month,
                        dia = viewModel.DataPublicacao.Day,
                        titulo = viewModel.Titulo,
                        id = viewModel.Id
                    }) + "#comentarios");
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("", exp.Message);
                }
            }
            preencherViewModel(post, viewModel, null);
            return View(viewModel);
        }
        #endregion
    }
}

BlogMichel.Web/Views/Blog/Index.cshtml
@model BlogMichel.Web.Models.Blog.ListarPostsViewModel
@{
    ViewBag.Title = "Post";
    var tipoPesquisa = "";
    if (Model.Tag != null)
    {
        tipoPesquisa = string.Format(" - Tag: {0}", Model.Tag);
    }
}
@section Scripts
{
    <script src="@Url.Content("~/Scripts/Views/Blog/Index.js")"></script>
}

<h1>Posts @tipoPesquisa</h1>
<div class="row">
    <div class="col-md-10">
     @foreach (var item in Model.Posts)  { <h2>@Html.ActionLink(item.Titulo, "Post", "Blog", new
   { id = item.Id,
       ano = item.DataPublicacao.Year,
       mes = item.DataPublicacao.Month,
       dia = item.DataPublicacao.Day,
       titulo = HttpUtility.UrlDecode(item.Titulo)
   }, null) </h2> 
    <div>
        <div class="icone-calendario div-imagem"></div>
        @item.DataPublicacao.ToString("dd/MM/yyyy HH:mm")
        <div class="icone-autor div-imagem"></div>
        @item.Autor
        <div class="icone-comentario div-imagem"></div>
        <a href="@Url.Action("Post", "Blog", new
            {
                id = item.Id,
                ano = item.DataPublicacao.Year,
                mes = item.DataPublicacao.Month,
                dia = item.DataPublicacao.Day,
                titulo = item.Titulo,
            })#comentarios">@item.QtdeComentarios</a>
        <div class="icone-editar div-imagem"></div>
        @Html.ActionLink("Editar","EditarPost", "Administracao", new { id = item.Id }, null)
        <div class="icone-excluir div-imagem"></div>
        @Html.ActionLink("Excluir", "ExcluirPost", "Administracao", new { id = item.Id }, new { @class = "excluir-post" })
    </div>
    <div>
        @item.Resumo
    </div>
    @Html.ActionLink("Continue lendo...", "Post", "Blog", new
{
    id = item.Id,
    ano = item.DataPublicacao.Year,
    mes = item.DataPublicacao.Month,
    dia = item.DataPublicacao.Day,
    titulo = HttpUtility.UrlDecode(item.Titulo)
}, null)
     }
  </div>
<div class="col-md-2">
<h3>Tags</h3>
<ul>
@foreach (var item in Model.Tags)
{
    <li>@Html.ActionLink(item, "Index", "Blog", new { tag = item }, null)</li>
}
 </ul>
</div>
</div>
 
    @Html.Partial("_Paginacao", Model)

BlogMichel.Web/Views/Blog/Post.cshtml
@model BlogMichel.Web.Models.Blog.DetalhesPostViewModel
@{
    ViewBag.Title = "Post";
}
@section Scripts
{
    <script src="@Url.Content("~/Scripts/Views/Blog/Index.js")"></script>
}
<h2>@Model.Titulo</h2>
<div class="cabecalho-post">
    <div class="icone-calendario div-imagem"></div>
    @Model.DataPublicacao.ToString("dd/MM/yyyy HH:mm")
    <div class="icone-autor div-imagem"></div>
    @Model.Autor
    <div class="icone-comentario div-imagem"></div>
    @Html.ActionLink(Model.QtdeComentarios.ToString(), "")
    <div class="icone-excluir div-imagem"></div>
    @Html.ActionLink("Excluir", "ExcluirPost", "Administracao", new { id = Model.Id }, new { @class = "excluir-post" })
</div>
<div class="descricao-post">
    @Model.Descricao
</div>
<div class="tags-post">
    <h3>Tags</h3>
    @if (Model.Tags != null)
    {
        foreach (var item in Model.Tags)
        {
        <li>
           @Html.ActionLink(item.Tag, "Index", "Blog", new { tag = item.Tag }, null)
        </li>
        }
    }
</div>
<div>
    <h3>Novo comentário</h3>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.HiddenFor(x => x.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.ComentarioNome)
            @Html.TextBoxFor(m => m.ComentarioNome, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ComentarioNome)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ComentarioEmail)
            @Html.TextBoxFor(m => m.ComentarioEmail, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ComentarioEmail)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ComentarioPaginaWeb)
            @Html.TextBoxFor(m => m.ComentarioPaginaWeb, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ComentarioPaginaWeb)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ComentarioDescricao)
            @Html.TextBoxFor(m => m.ComentarioDescricao, new { rows = 8, @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ComentarioDescricao)
        </div>
        <p>
            <input type="submit" value="Salvar" class="btn btn-primary"
        </p>
    }
    <div id="comentarios">
        <h3>Comentários</h3>
        @{
            var contador = 0;
        }
        @foreach (var item in Model.Comentarios)
        {
            contador++;
            string id = "comentario" + contador.ToString();
            string cssClass = "text-info";
            if (item.AdmPost)
            {
                cssClass = "label label-info";
            }
            <div>
                <a id="@item.Id"></a>
                <p>
                    <span class="@cssClass">@item.Nome</span><br />
                    <small>
                        @item.DataHora.ToString("dd/MM/yyyy HH:mm:ss")
                        @if (!string.IsNullOrEmpty(item.PaginaWeb))
                        {
                            <text>|</text>
                            <a href="@item.PaginaWeb">@item.PaginaWeb</a>
                        }
                        @if (this.Request.IsAuthenticated)
                        {
                            <text>|</text>
                            @Html.ActionLink("Remover", "ExcluirComentario", "Administracao", new { id = item.Id }, new { @class = "excluir-comentario" })
                        }
                    </small>
                </p>
                @Html.Raw(Html.Encode(item.Descriçao).Replace("\n", "<br />"))
            </div>

            if (contador < this.Model.Comentarios.Count)
            {
                <hr />
            }
        }
    </div>

BlogMichel.Web/Views/Blog/_Paginacao.cshtml
@model BlogMichel.Web.Models.Blog.ListarPostsViewModel
@if (Model.TotalPaginas > 1)
{
    var proximaPagina = Model.PaginaAtual + 1;
    var paginaAnterior = Model.PaginaAtual - 1;

    <div class="pagination">
        @if (Model.PaginaAtual > 1)
        {
            @Html.ActionLink("Página anterior", "Index", "Blog", new { pagina = paginaAnterior, tag = Model.Tag, pesquisa = Model.Pesquisa
         }, new { rel = "prev" })           
        }
        @if (Model.PaginaAtual < Model.TotalPaginas)
        {
            @Html.ActionLink("Próxima Pagina", "Index", "Blog", new { pagina = proximaPagina, tag = Model.Tag, pesquisa = Model.Pesquisa }, new { rel = "prev" })         
        }
    </div>
  
        }